# see https://symfony.com/doc/current/reference/configuration/framework.html
# source aide : https://forum.ovh.com/showthread.php/109111-Probl%C3%A8me-de-persistance-de-sessions-sur-Mutu-Pro
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: 'session.handler.native_file'
        save_path: '%kernel.project_dir%/../sessions/%kernel.environment%'
        cookie_lifetime: 2592000
        gc_maxlifetime: 2592000
        gc_probability: 1
        cookie_secure: 'auto'
        cookie_samesite: 'lax'

        #handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler

    #esi: true
    #fragments: ~
    php_errors:
        log: true
